### ISSUE TITLE
Doesn't work in FF 35.01

### ISSUE THREAD

**Issue by adriank** [the-control-group/app-chart#4]
TypeError: this.$.series.getDistributedNodes(...).array is not a function
CgogICA...GF0dHJu (line 116, col 22)
TypeError: this.$.options.getDistributedNodes(...).array is not a function
